In [1]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
import cmath
import os

In [8]:
A = np.array([i for i in range(0, 253, 4)])
B = np.zeros(8)
C = np.array([0, 0, 1, 1, 1, 1, 0, 0])
C 

array([0, 0, 1, 1, 1, 1, 0, 0])

Création de I1, I2 et I3

In [10]:
#I1
I1 = A
for i in range(0,63) :
    I1 = np.vstack([I1,A])
#I2
I2 = np.array([B,B,C,C,C,C,B,B])
#I3
I3 = np.column_stack((I2, I2)) #ajouter les colonnes
I3 = np.vstack((I3, I3)) #ajouter les lignes
print("I1 = \n",I1)
print("Dimensions de I1 = ",I1.shape)
print("I2 = \n",I2)
print("I3 = \n",I3)

I1 = 
 [[  0   4   8 ... 244 248 252]
 [  0   4   8 ... 244 248 252]
 [  0   4   8 ... 244 248 252]
 ...
 [  0   4   8 ... 244 248 252]
 [  0   4   8 ... 244 248 252]
 [  0   4   8 ... 244 248 252]]
Dimensions de I1 =  (64, 64)
I2 = 
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
I3 = 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 0. 0. 0. 0.

Conversion

In [11]:
I1 = np.uint8(I1)
I2 = np.uint8(I2)
I3 = np.uint8(I3)

Visualisation avec OpenCV (ca ouvre une fenêtre)

In [12]:
cv.imshow("Matrice I1", I1)
cv.waitKey(0)
cv.imshow("Matrice I2", I2)
cv.waitKey(0)
cv.imshow("Matrice I3", I3)
cv.waitKey(0)
cv.destroyAllWindows()